defaults:
  - _self_
  - problem: mt_routefinder_unified
  - llm_client: openai
  - override hydra/output: local

hydra:
  job:
    name: ${problem.problem_name}-${problem.problem_type}
    chdir: True

algorithm: hercules
max_fe: 100
pop_size: 10
init_pop_size: 10
mutation_rate: 0.5
timeout: 500
diversify_init_pop: True